language: python
python:
    - 3.8

services:
    - docker
    
before_script:
    - pip install docker-compose
    - docker-compose up -d --build


script:
    - docker-compose exec backend python manage.py test
    - docker-compose exec backend flake8 --config=.flake8